version: '3'

services:
  redis:
    image: redis:4.0.9-alpine
    ports:
      - "6379:6379"

  # fixed according this: https://gist.github.com/crackcomm/9b13a7542bf50647409b311caae22802
  nsqlookup:
    image: nsqio/nsq:v0.3.8
    hostname: nsqlookup
    ports:
      - "4160:4160"
      - "4161:4161"
    command: /nsqlookupd

  nsq:
    image: nsqio/nsq:v0.3.8
    hostname: nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    links:
      - nsqlookup:nsqlookup
    command: /nsqd --broadcast-address nsq --lookupd-tcp-address=nsqlookup:4160

  nsqadmin:
    image: nsqio/nsq:v0.3.8
    hostname: nsqadmin
    links:
      - nsqlookup:nsqlookup
    ports:
      - "4171:4171"
    command: /nsqadmin --lookupd-http-address=nsqlookup:4161
